name: analysis_tools_ci
channels:
  - conda-forge
dependencies:
  - black
  - cftime
  - cf-units
  - dask
  - flake8
  - intake
  - intake-esm
  - netCDF4
  - numpy
  - packaging
  - pandas
  - pytest
  - pyyaml
  - xarray
